### ISSUE TITLE
task_03

### ISSUE THREAD

**Issue by Duferig** [brstu/OTIS-2023#266]
Вы приняли мою третью лабораторную работу и объединили мою ветку с веткой main, но факт выполнения лабораторной работы не отображается в виде галочки в таблице в readme.md.

**Comment by idzm** [comment]
Надо отдельным запросом внести изменения в таблице в `readme.md`.

**Comment by Duferig** [comment]
> Надо отдельным запросом внести изменения в таблице в `readme.md`.

Сделал отдельным запросом
