### ISSUE TITLE
Не пропускает пулл реквест из-за code duplication на чужие файлы

### ISSUE THREAD

**Issue by RuuuuuD3** [brstu/OTIS-2023#370]
![Снимок](https://github.com/brstu/OTIS-2023/assets/144435170/558ad90d-9735-4ed3-916b-345541710304)

Конфликтующие файлы:

1. https://github.com/brstu/OTIS-2023/blob/08266eed4164c33b43a85b6db8e6e9a7ee251991/trunk/II02302/task_02/src/qwerty.cpp
2. https://github.com/brstu/OTIS-2023/blob/08266eed4164c33b43a85b6db8e6e9a7ee251991/trunk/ii02305/src/task_02.cpp
3. https://github.com/brstu/OTIS-2023/blob/08266eed4164c33b43a85b6db8e6e9a7ee251991/trunk/II02402/task_04/doc/report.md
4. https://github.com/brstu/OTIS-2023/blob/08266eed4164c33b43a85b6db8e6e9a7ee251991/trunk/ii02412/task_04/doc/report.md

@RuuuuuD3 in https://github.com/brstu/OTIS-2023/pull/294

**Comment by RuuuuuD3** [comment]
Данная проблема появилась в 5 лабе #296

**Comment by idzm** [comment]
Проблема с дублированием в уже принятых запросах решена.
