### ISSUE TITLE
task 3 

### ISSUE THREAD

**Issue by Eliza0756** [brstu/OTIS-2023#389]
Вознникли проблемы с проверкой [Check for duplicate code](https://github.com/brstu/OTIS-2023/actions/runs/7265469526/job/19795210492?pr=332#logs)
![photo_2023-12-19_21-06-19](https://github.com/brstu/OTIS-2023/assets/145442986/4b3654ba-8e00-4c8e-9730-dbadc4979e35)
Жалобы на файлы readme.md > 90%

**Comment by idzm** [comment]
Решено здесь - https://github.com/brstu/OTIS-2023/commit/bbc41470410f44cff69842dd51949694bf7dd292.
